### ISSUE TITLE
Godot debugging process does not work with new update. (Project is abandoned?)

### ISSUE THREAD

**Issue by oncoremarco** [godotengine/godot-csharp-vscode#64] opened 2024-04-27 00:00 UTC
When using Godot 4.2.1 and version 2.0.0 of the VS Code plugin, debugging seems completely broken. Play In Editor does not activate the editor, "Launch" launches a copy of the project in the editor but not in a way that allows the running project to be debugged, and Attach does nothing. 

To reproduce this issue, follow the following steps: 

- In a new project, go to ">C# Godot: Generate Assets for Build and Debug"
- in the "Launch.json" and "task.json" files, change the "<insert-godot-executable-path-here>" to the godot executable path.
- Attempt to run the project using the debugger

And it will fail. 

I'm concerned that this extension seems to have been abandoned by the developer, as my research indicates it seems many people have had issues getting this working over the last couple of years, and no solution has been provided. The 2.0.0 update seems to have brought new problems with it as well, and I've seen no cases anyone successfully getting it to work.

Thank you.

**Comment by raulsntos** [comment] 2024-04-27 02:00
This extension only supports Godot 3.x. For Godot 4.x you don't need to use this extension for debugging, you can use the normal Microsoft C# extension. See the [Godot documentation](https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_basics.html#visual-studio-code) for instructions.

Closing as a duplicate of https://github.com/godotengine/godot-csharp-vscode/issues/43.

**Closed as not planned by raulsntos** 2024-04-27 02:00 UTC
Labels: bug, archived

**Comment by nielpattin** [comment] 2024-04-29 10:42
> This extension only supports Godot 3.x. For Godot 4.x you don't need to use this extension for debugging, you can use the normal Microsoft C# extension. See the [Godot documentation](https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_basics.html#visual-studio-code) for instructions.
> 
> Closing as a duplicate of #43.

I follow the introduction but it only Play the main scene. But, how do I make it to run debug on the current selected screen in the editor? I only want to test some specific scenes.

**Comment by raulsntos** [comment] 2024-04-29 15:01
You can specify the scene in the arguments, for example:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Play",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${env:GODOT4}",
            "args": ["${workspaceFolder}/MyScene.tscn"],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
        }
    ]
}
```

See more information about the available arguments in the [_Command line tutorial_](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html) documentation page.

**Comment by nielpattin** [comment] 2024-04-29 15:03
I guess this is the only current solution for now.
